/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjetosImport } from './routes/projetos'
import { Route as HabilidadesImport } from './routes/habilidades'
import { Route as ContatoImport } from './routes/contato'
import { Route as ArtigosImport } from './routes/artigos'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProjetosRoute = ProjetosImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRoute,
} as any)

const HabilidadesRoute = HabilidadesImport.update({
  id: '/habilidades',
  path: '/habilidades',
  getParentRoute: () => rootRoute,
} as any)

const ContatoRoute = ContatoImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRoute,
} as any)

const ArtigosRoute = ArtigosImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosImport
      parentRoute: typeof rootRoute
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoImport
      parentRoute: typeof rootRoute
    }
    '/habilidades': {
      id: '/habilidades'
      path: '/habilidades'
      fullPath: '/habilidades'
      preLoaderRoute: typeof HabilidadesImport
      parentRoute: typeof rootRoute
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/habilidades': typeof HabilidadesRoute
  '/projetos': typeof ProjetosRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/habilidades': typeof HabilidadesRoute
  '/projetos': typeof ProjetosRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/habilidades': typeof HabilidadesRoute
  '/projetos': typeof ProjetosRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artigos' | '/contato' | '/habilidades' | '/projetos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artigos' | '/contato' | '/habilidades' | '/projetos'
  id: '__root__' | '/' | '/artigos' | '/contato' | '/habilidades' | '/projetos'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosRoute: typeof ArtigosRoute
  ContatoRoute: typeof ContatoRoute
  HabilidadesRoute: typeof HabilidadesRoute
  ProjetosRoute: typeof ProjetosRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosRoute: ArtigosRoute,
  ContatoRoute: ContatoRoute,
  HabilidadesRoute: HabilidadesRoute,
  ProjetosRoute: ProjetosRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/artigos",
        "/contato",
        "/habilidades",
        "/projetos"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/artigos": {
      "filePath": "artigos.tsx"
    },
    "/contato": {
      "filePath": "contato.tsx"
    },
    "/habilidades": {
      "filePath": "habilidades.tsx"
    },
    "/projetos": {
      "filePath": "projetos.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
