/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ArtigosImport } from './routes/artigos'

// Create Virtual Routes

const ProjetosLazyImport = createFileRoute('/projetos')()
const HabilidadesLazyImport = createFileRoute('/habilidades')()
const ContatoLazyImport = createFileRoute('/contato')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ProjetosLazyRoute = ProjetosLazyImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projetos.lazy').then((d) => d.Route))

const HabilidadesLazyRoute = HabilidadesLazyImport.update({
  id: '/habilidades',
  path: '/habilidades',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/habilidades.lazy').then((d) => d.Route))

const ContatoLazyRoute = ContatoLazyImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contato.lazy').then((d) => d.Route))

const ArtigosRoute = ArtigosImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosImport
      parentRoute: typeof rootRoute
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoLazyImport
      parentRoute: typeof rootRoute
    }
    '/habilidades': {
      id: '/habilidades'
      path: '/habilidades'
      fullPath: '/habilidades'
      preLoaderRoute: typeof HabilidadesLazyImport
      parentRoute: typeof rootRoute
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoLazyRoute
  '/habilidades': typeof HabilidadesLazyRoute
  '/projetos': typeof ProjetosLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoLazyRoute
  '/habilidades': typeof HabilidadesLazyRoute
  '/projetos': typeof ProjetosLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoLazyRoute
  '/habilidades': typeof HabilidadesLazyRoute
  '/projetos': typeof ProjetosLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artigos' | '/contato' | '/habilidades' | '/projetos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artigos' | '/contato' | '/habilidades' | '/projetos'
  id: '__root__' | '/' | '/artigos' | '/contato' | '/habilidades' | '/projetos'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ArtigosRoute: typeof ArtigosRoute
  ContatoLazyRoute: typeof ContatoLazyRoute
  HabilidadesLazyRoute: typeof HabilidadesLazyRoute
  ProjetosLazyRoute: typeof ProjetosLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ArtigosRoute: ArtigosRoute,
  ContatoLazyRoute: ContatoLazyRoute,
  HabilidadesLazyRoute: HabilidadesLazyRoute,
  ProjetosLazyRoute: ProjetosLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/artigos",
        "/contato",
        "/habilidades",
        "/projetos"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/artigos": {
      "filePath": "artigos.tsx"
    },
    "/contato": {
      "filePath": "contato.lazy.tsx"
    },
    "/habilidades": {
      "filePath": "habilidades.lazy.tsx"
    },
    "/projetos": {
      "filePath": "projetos.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
